apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: vibrational-intelligence
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: vibrational-intelligence
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
  clusterIP: None

