apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: vibrational-intelligence
spec:
  selector:
    app: milvus
  ports:
  - port: 19530
    targetPort: 19530
    name: milvus
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-headless
  namespace: vibrational-intelligence
spec:
  selector:
    app: milvus
  ports:
  - port: 19530
    targetPort: 19530
  clusterIP: None

