apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: vibrational-intelligence
spec:
  selector:
    app: neo4j
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
  - port: 7474
    targetPort: 7474
    name: http
  type: ClusterIP

