[package]
name = "almi-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "almi_native"
crate-type = ["cdylib"]

[dependencies]
almi-core.workspace = true
almi-continuity.workspace = true
almi-cosmos.workspace = true
pyo3.workspace = true
serde_json.workspace = true
