[package]
name = "lighttoken-spectrum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lighttoken-core.workspace = true
rustfft.workspace = true
thiserror.workspace = true
libloading.workspace = true

[dev-dependencies]
serde_json.workspace = true
proptest.workspace = true
tempfile.workspace = true
